Carefully release NBL in Windows
openvswitch/ovs pull request #385
Opened 2022-05-09 08:22 UTC by hxietkg

OvsExtSendNBLComplete always release NBLs with flag SINGL_SOURCE, this is an
efficient way, which requires all the NBLs having the same source port, when
cloned/fragment NBLs are released, the parent NBLs will be released as well,
the problem is that a parent NBL may have a different source port from the
cloned/fragment NBL, so releasing the parent NBLs with flag SINGLE_SOURCE
is not corrct, see:
    https://github.com/microsoft/hcsshim/issues/1056

When this happens, commands 'Get-NetAdapter' and 'Get-HnsEndpoint' in the
Windows node show that one net-adapter/hns-endpoint is in 'disconnected'
state, meanwhile, following processes are affected, ecah of them has one
thread pending on a lock:
  vmcompute.exe
  containerd.exe
  antrea-agent.exe

To fix this issue, we may check SourcePortId in each parent NBLs before
released.

A simple way to reprodue this issue:
   1, Enable encap mode
   2, create 2 nodes, nodeA and nodeB
   3, create podA with image k8s.gcr.io/e2e-test-images/agnhost:2.21 on
      nodeA, run 'iperf/iperf.exe -s -p 9000 -D'
   4, create podB with same image on nodeB, run command
      'iperf/iperf.exe -c <podA-ip> -p 9000'
   5, delete podB
   6, run 'Get-NetAdapter' on nodeB, you will find the leaked net adapter.

2022-05-17 08:29 UTC, aserdean requested changes
Please provide a signed off in order to comply with our [Developer’s Certificate of Origin](https://docs.openvswitch.org/en/latest/internals/contributing/submitting-patches/#developer-s-certificate-of-origin)

2022-05-17 08:29 UTC, aserdean commented on datapath-windows/ovsext/PacketIO.c
> +    if (singleSource) {
Please move this logic to a single function.
It will improve readability

2022-05-17 10:44 UTC, hxietkg commented
@aserdean thanks a lot!

2022-05-17 14:57 UTC, hxietkg commented
> Please provide a signed off in order to comply with our [Developer’s Certificate of Origin](https://docs.openvswitch.org/en/latest/internals/contributing/submitting-patches/#developer-s-certificate-of-origin)

added

2022-05-25 19:05 UTC, aserdean commented
I applied this patch on master and backported it until branch-2.13

Thanks a lot for the patch and all the testing @hxietkg!

2022-05-25 19:05 UTC, closed without merging